# Generated by Django 5.1.1 on 2024-12-07 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet_registration', '0001_initial'),
        ('veterinarians', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='primary_veterinarian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_pets', to='veterinarians.veterinarianprofile'),
        ),
    ]
